kind: ConfigMap
apiVersion: v1
metadata:
  name: notificationsapi-cm
  # namespace: {{ .Values.namespace }}
  labels:
    app: pokebay
    service: notificationsapi
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://0.0.0.0:80
  SeqServerUrl: http://seq

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: notificationsapi
  # namespace: {{ .Values.namespace }}
  labels:
    app: pokebay
    service: notificationsapi
spec:
  replicas: 1
  selector:
    matchLabels:
      service: notificationsapi
  template:
    metadata:
      labels:
        app: pokebay
        service: notificationsapi
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "notificationsapi"
        dapr.io/app-port: "80"
        dapr.io/config: "dapr-config"
        dapr.io/log-as-json: "true"
    spec:
      containers:
        - name: notificationsapi
          image: grailseekerdocker/pokebay:notificationsapi
          # imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: notificationsapi-cm
          # readinessProbe:
          #   httpGet:
          #     path: /hc
          #     port: 80
          #   initialDelaySeconds: 5
          #   periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: notificationsapi
  # namespace: {{ .Values.namespace }}
  labels:
    app: pokebay
    service: notificationsapi
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
      protocol: TCP
      name: http
  selector:
    service: notificationsapi