version: '3.4'

services:
  
  #rabbitmq:
  #  image: rabbitmq:3-management-alpine
  #  container_name: pokebay_rabbitmq
  #  ports:
  #    - "5672:5672"
  
  redis:
    image: redis:alpine
    container_name: pokebay_redis
    ports:
      - "6379:6379"

  zipkin:
    image: openzipkin/zipkin
    container_name: pokebay_zipkin
    ports:
      - "9411:9411"

  dapr-placement:
    image: "daprio/dapr:1.0.0"
    container_name: pokebay_dapr-placement
    command: ["./placement", "-port", "50000", "-log-level", "debug"]
    ports:
      - "50000:50000"

  seq:
    image: datalust/seq:latest
    container_name: pokebay_seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"

  smtp4dev:
    image: rnwood/smtp4dev:v3
    container_name: pokebay_smtp
    restart: always
    ports:
      - "3000:80"
      - "2525:25"

  pokebaytestui:
    image: ${DOCKER_REGISTRY-}pokebaytestui
    build:
      context: .
      dockerfile: PokEBayTestUI/Dockerfile

  pokebaytestui-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "pokebaytestui", "-app-port", "80", "-components-path", "/components", "-config", "/configuration/pokebay-config.yaml" ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
    depends_on:
      - pokebaytestui
    network_mode: "service:pokebaytestui"

  pokebay.basket.api:
    image: ${DOCKER_REGISTRY-}pokebaybasketapi
    build:
      context: .
      dockerfile: PokEBay.Basket.API/Dockerfile
    depends_on:
      - redis
      - seq
    ports:
      - "5103:80"

  pokebay.basket.api-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "pokebaybasketapi", "-app-port", "80", "-components-path", "/components",  "-config", "/configuration/pokebay-config.yaml" ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
    depends_on:
      - pokebay.basket.api
    network_mode: "service:pokebay.basket.api"

  pokebay.ui:
    image: ${DOCKER_REGISTRY-}pokebayui
    build:
      context: .
      dockerfile: PokEBay.UI/Dockerfile
    depends_on:
      - pokebay.basket.api
      - pokebay.catalog.api
      - pokebay.orders.api
      - pokebay.notifications.api
      - seq
    ports:
      - "5104:80"

  pokebay.ui-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "pokebayui", "-app-port", "80", "-components-path", "/components", "-config", "/configuration/pokebay-config.yaml" ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
    depends_on:
      - pokebay.ui
    network_mode: "service:pokebay.ui"

  pokebay.catalog.api:
    image: ${DOCKER_REGISTRY-}pokebaycatalogapi
    build:
      context: .
      dockerfile: PokEBay.Catalog.API/Dockerfile
    depends_on:
      - seq
    ports:
      - "5101:80"

  pokebay.catalog.api-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "pokebaycatalogapi", "-app-port", "80", "-components-path", "/components", "-config", "/configuration/pokebay-config.yaml" ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
    depends_on:
      - pokebay.catalog.api
    network_mode: "service:pokebay.catalog.api"

  pokebay.orders.api:
    image: ${DOCKER_REGISTRY-}pokebayordersapi
    build:
      context: .
      dockerfile: PokEBay.Orders.API/Dockerfile
    depends_on:
      - redis
      - seq
    ports:
      - "5102:80"

  pokebay.orders.api-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "pokebayordersapi", "-app-port", "80", "-components-path", "/components", "-config", "/configuration/pokebay-config.yaml" ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
    depends_on:
      - pokebay.orders.api
    network_mode: "service:pokebay.orders.api"

  pokebay.notifications.api:
    image: ${DOCKER_REGISTRY-}pokebaynotificationsapi
    build:
      context: .
      dockerfile: PokEBay.Notifications.API/Dockerfile
    depends_on:
      - seq
      - redis
    ports:
      - "5108:80"

  pokebay.notifications.api-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "pokebaynotificationsapi", "-app-port", "80", "-components-path", "/components", "-config", "/configuration/pokebay-config.yaml" ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
    depends_on:
      - pokebay.notifications.api
    network_mode: "service:pokebay.notifications.api"