version: '3.4'

services:
  pokebaytestui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  pokebay.basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  pokebay.ui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - PATH_BASE=/pokebay.ui
      - PORT=80
      - Serilog__MinimumLevel__Override__pokebay.ui=Verbose
      #- ASPNETCORE_URLS=https://+:443;http://+:80
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=grailseeker@123
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/https/PokEBay.UI.pfx
    #ports:      
      #- "80"
      #- "443"
    #volumes:
    #  - ~/.aspnet/https:/https:ro
      #- ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  pokebay.catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  pokebay.orders.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  pokebay.notifications.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - PATH_BASE=/pokebay.notifications.api
      - PORT=80
      - Serilog__MinimumLevel__Override__pokebay.notifications.api=Verbose
    #  - ASPNETCORE_URLS=https://+:443;http://+:80
    #  - ASPNETCORE_Kestrel__Certificates__Default__Password=grailseeker@123
    #  - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/pokebay.notifications.pfx
    #ports:
    #  - "80"
    #  - "443"
    #volumes:
    #  - ~/.aspnet/https:/https:ro

