apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pokebay-pubsub
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    value: "amqp://localhost:5672"
  - name: durable
    value: true
